sampleSOQLDemo1.sampleSoql1();
sampleSOQLDemo1.sampleSoql2();
sampleSOQLDemo1.sampleSoql3('Yes');
sampleSOQLDemo1.sampleSoql4('Closed Won');
// (Opportunity:{Name=Express Logistics Standby Generator, Id=0065e000007fZISAA2}, Opportunity:{Name=GenePoint Standby Generator, Id=0065e000007fZITAA2}, Opportunity:{Name=United Oil SLA, Id=0065e000007fZIWAA2}, Opportunity:{Name=Edge Emergency Generator, Id=0065e000007fZIYAA2}, Opportunity:{Name=University of AZ Portable Generators, Id=0065e000007fZIZAA2}, Opportunity:{Name=GenePoint SLA, Id=0065e000007fZIdAAM}, Opportunity:{Name=Edge Installation, Id=0065e000007fZIfAAM}, Opportunity:{Name=Edge SLA, Id=0065e000007fZIgAAM}, Opportunity:{Name=United Oil Installations, Id=0065e000007fZIhAAM}, Opportunity:{Name=Grand Hotels Generator Installations, Id=0065e000007fZIiAAM}, ...)

sampleSOQLDemo1.sampleSoql5('Web', 'Closed Won');
