public class SampleClass2 {
    public void sampleMethod(){
        System.debug('A message from sample class 2');
        System.debug('Another Message from Sample Class 2');
        System.debug('one more debug');

    }
    //parametrized method
    public void printIt(string printString){
        System.debug('print string ' + printString);
    }

    //Create a method which takes two integer.
    //return the sum of those two integer.

    public integer add(integer int1, integer int2){
        integer sum = int1 +int2;
        

    }

}
